/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { TreasuryMock } from "../TreasuryMock";

export class TreasuryMock__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(weth_: string, overrides?: Overrides): Promise<TreasuryMock> {
    return super.deploy(weth_, overrides || {}) as Promise<TreasuryMock>;
  }
  getDeployTransaction(
    weth_: string,
    overrides?: Overrides
  ): TransactionRequest {
    return super.getDeployTransaction(weth_, overrides || {});
  }
  attach(address: string): TreasuryMock {
    return super.attach(address) as TreasuryMock;
  }
  connect(signer: Signer): TreasuryMock__factory {
    return super.connect(signer) as TreasuryMock__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TreasuryMock {
    return new Contract(address, _abi, signerOrProvider) as TreasuryMock;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IERC20",
        name: "weth_",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "pull",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "weth",
    outputs: [
      {
        internalType: "contract IERC20",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x60a060405234801561001057600080fd5b5060405161023c38038061023c8339818101604052602081101561003357600080fd5b5051606081901b6001600160601b0319166080526001600160a01b03166101d161006b6000398060a9528061012052506101d16000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80633fc8cef31461003b578063f2d5d56b1461006c575b600080fd5b6100436100a7565b6040805173ffffffffffffffffffffffffffffffffffffffff9092168252519081900360200190f35b6100a56004803603604081101561008257600080fd5b5073ffffffffffffffffffffffffffffffffffffffff81351690602001356100cb565b005b7f000000000000000000000000000000000000000000000000000000000000000081565b604080517f23b872dd00000000000000000000000000000000000000000000000000000000815273ffffffffffffffffffffffffffffffffffffffff84811660048301523060248301526044820184905291517f0000000000000000000000000000000000000000000000000000000000000000909216916323b872dd916064808201926020929091908290030181600087803b15801561016b57600080fd5b505af115801561017f573d6000803e3d6000fd5b505050506040513d602081101561019557600080fd5b5050505056fea2646970667358221220c852486b737445e7c49d765c617550b6c53b56ddd285ecf50dd9c14e0011cfd964736f6c634300060a0033";
