/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface TLMProxyInterface extends ethers.utils.Interface {
  functions: {
    "FYDAI()": FunctionFragment;
    "UNIT()": FunctionFragment;
    "WETH()": FunctionFragment;
    "borrow(bytes32,uint256,bytes32,address,uint256)": FunctionFragment;
    "controller()": FunctionFragment;
    "tlm()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "FYDAI", values?: undefined): string;
  encodeFunctionData(functionFragment: "UNIT", values?: undefined): string;
  encodeFunctionData(functionFragment: "WETH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "borrow",
    values: [BytesLike, BigNumberish, BytesLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "controller",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "tlm", values?: undefined): string;

  decodeFunctionResult(functionFragment: "FYDAI", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "UNIT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "WETH", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "borrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "controller", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tlm", data: BytesLike): Result;

  events: {};
}

export class TLMProxy extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  listeners<T, G>(
    eventFilter?: TypedEventFilter<T, G>
  ): Array<TypedListener<T, G>>;
  off<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  on<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  once<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  removeListener<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  removeAllListeners<T, G>(eventFilter: TypedEventFilter<T, G>): this;

  queryFilter<T, G>(
    event: TypedEventFilter<T, G>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<T & G>>>;

  interface: TLMProxyInterface;

  functions: {
    FYDAI(overrides?: CallOverrides): Promise<[string]>;

    "FYDAI()"(overrides?: CallOverrides): Promise<[string]>;

    UNIT(overrides?: CallOverrides): Promise<[BigNumber]>;

    "UNIT()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    WETH(overrides?: CallOverrides): Promise<[string]>;

    "WETH()"(overrides?: CallOverrides): Promise<[string]>;

    borrow(
      collateral: BytesLike,
      maturity: BigNumberish,
      ilk: BytesLike,
      to: string,
      fyDaiToBorrow: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "borrow(bytes32,uint256,bytes32,address,uint256)"(
      collateral: BytesLike,
      maturity: BigNumberish,
      ilk: BytesLike,
      to: string,
      fyDaiToBorrow: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    controller(overrides?: CallOverrides): Promise<[string]>;

    "controller()"(overrides?: CallOverrides): Promise<[string]>;

    tlm(overrides?: CallOverrides): Promise<[string]>;

    "tlm()"(overrides?: CallOverrides): Promise<[string]>;
  };

  FYDAI(overrides?: CallOverrides): Promise<string>;

  "FYDAI()"(overrides?: CallOverrides): Promise<string>;

  UNIT(overrides?: CallOverrides): Promise<BigNumber>;

  "UNIT()"(overrides?: CallOverrides): Promise<BigNumber>;

  WETH(overrides?: CallOverrides): Promise<string>;

  "WETH()"(overrides?: CallOverrides): Promise<string>;

  borrow(
    collateral: BytesLike,
    maturity: BigNumberish,
    ilk: BytesLike,
    to: string,
    fyDaiToBorrow: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "borrow(bytes32,uint256,bytes32,address,uint256)"(
    collateral: BytesLike,
    maturity: BigNumberish,
    ilk: BytesLike,
    to: string,
    fyDaiToBorrow: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  controller(overrides?: CallOverrides): Promise<string>;

  "controller()"(overrides?: CallOverrides): Promise<string>;

  tlm(overrides?: CallOverrides): Promise<string>;

  "tlm()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    FYDAI(overrides?: CallOverrides): Promise<string>;

    "FYDAI()"(overrides?: CallOverrides): Promise<string>;

    UNIT(overrides?: CallOverrides): Promise<BigNumber>;

    "UNIT()"(overrides?: CallOverrides): Promise<BigNumber>;

    WETH(overrides?: CallOverrides): Promise<string>;

    "WETH()"(overrides?: CallOverrides): Promise<string>;

    borrow(
      collateral: BytesLike,
      maturity: BigNumberish,
      ilk: BytesLike,
      to: string,
      fyDaiToBorrow: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "borrow(bytes32,uint256,bytes32,address,uint256)"(
      collateral: BytesLike,
      maturity: BigNumberish,
      ilk: BytesLike,
      to: string,
      fyDaiToBorrow: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    controller(overrides?: CallOverrides): Promise<string>;

    "controller()"(overrides?: CallOverrides): Promise<string>;

    tlm(overrides?: CallOverrides): Promise<string>;

    "tlm()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    FYDAI(overrides?: CallOverrides): Promise<BigNumber>;

    "FYDAI()"(overrides?: CallOverrides): Promise<BigNumber>;

    UNIT(overrides?: CallOverrides): Promise<BigNumber>;

    "UNIT()"(overrides?: CallOverrides): Promise<BigNumber>;

    WETH(overrides?: CallOverrides): Promise<BigNumber>;

    "WETH()"(overrides?: CallOverrides): Promise<BigNumber>;

    borrow(
      collateral: BytesLike,
      maturity: BigNumberish,
      ilk: BytesLike,
      to: string,
      fyDaiToBorrow: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "borrow(bytes32,uint256,bytes32,address,uint256)"(
      collateral: BytesLike,
      maturity: BigNumberish,
      ilk: BytesLike,
      to: string,
      fyDaiToBorrow: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    controller(overrides?: CallOverrides): Promise<BigNumber>;

    "controller()"(overrides?: CallOverrides): Promise<BigNumber>;

    tlm(overrides?: CallOverrides): Promise<BigNumber>;

    "tlm()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    FYDAI(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "FYDAI()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    UNIT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "UNIT()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    WETH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "WETH()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    borrow(
      collateral: BytesLike,
      maturity: BigNumberish,
      ilk: BytesLike,
      to: string,
      fyDaiToBorrow: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "borrow(bytes32,uint256,bytes32,address,uint256)"(
      collateral: BytesLike,
      maturity: BigNumberish,
      ilk: BytesLike,
      to: string,
      fyDaiToBorrow: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    controller(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "controller()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tlm(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "tlm()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
